index:
    path: /
    controller: App\Controller\TaskController::index

finish:
    path: /tasks/finish/{id}
    controller: App\Controller\TaskController::finish

delete:
    path: /tasks/delete/{id}
    controller: App\Controller\TaskController::delete

update:
    path: /tasks/update/{id}
    controller: App\Controller\TaskController::update

login: 
    path: /login
    controller: App\Controller\UserController::login

logout:
    path: /logout
    controller: App\Controller\UserController::logout

register: 
    path: /register
    controller: App\Controller\UserController::register

profile:
    path: /profile
    controller: App\Controller\UserController::profile

# creamos una ruta para resetear contraseña:
send_reset_email:
    path: /send_reset_email
    controller: App\Controller\UserController::send_reset_email